# Setup
title: K-HA$H
url: Amen02kh.github.io
#paginate: 4
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Amen Allah Khalfallah
  email: khamen.02@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Archive
    url: /archive
  - title: Categories
    url: /categories
  - title: About
    url: /about
  
